#version: '3.8'
#
#services:
#  app-consumer:
#    env_file:
#      - .env
#    ports:
#      - "8081:8080"
#    build:
#      context: .
#    environment:
#      - SPRING_RABBITMQ_HOST=rabbitmq
#      - SPRING_RABBITMQ_PORT=5672
#      - SPRING_RABBITMQ_USERNAME=guest
#      - SPRING_RABBITMQ_PASSWORD=guest
