spring:
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USER}
    password: ${RABBITMQ_PASS}
    virtual-host: ${RABBITMQ_VHOST}
    ssl:
      enabled: true
  config:
    activate:
      on-profile:
        active: prod

sendgrid:
  api-key: ${SENDGRID_API_KEY}

server:
  port: 8081

email:
  from: ${FROM_EMAIL_ADDRESS}
  to: ${TO_EMAIL_ADDRESS}