spring:
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USER:guest}
    password: ${RABBITMQ_PASS:guest}
  config:
    activate:
      on-profile:
        active: dev

sendgrid:
  api-key: ${SENDGRID_API_KEY}

server:
  port: 8081

email:
  from: ${FROM_EMAIL_ADDRESS}
  to: ${TO_EMAIL_ADDRESS}